#!/bin/bash
# Adobe MCP Multi-Agent Launcher

echo "Adobe MCP Multi-Agent Development"
echo "================================"
echo ""
echo "This project uses multiple Claude instances for parallel development."
echo "Each agent has specific instructions in AGENT_INSTRUCTIONS_*.md files."
echo ""
echo "Phase 1 Agents (Start Now):"
echo "1. UXP Research Agent"
echo "   Instructions: AGENT_INSTRUCTIONS_UXP_RESEARCH.md"
echo "   Focus: Research UXP capabilities and automation"
echo ""
echo "2. Environment Fix Agent"
echo "   Instructions: AGENT_INSTRUCTIONS_ENV_FIXES.md"
echo "   Focus: Fix WSL/Windows path issues"
echo ""
echo "3. Deployment Agent"
echo "   Focus: Automated UXP plugin deployment"
echo ""
echo "Phase 2 Agents (After Research):"
echo "4. Premiere Development Agent"
echo "   Instructions: AGENT_INSTRUCTIONS_PREMIERE.md"
echo "   Focus: Complete Premiere Pro implementation"
echo ""
echo "5. Illustrator Enhancement Agent"
echo "   Focus: Expand Illustrator features"
echo ""
echo "To launch an agent:"
echo "  claude [agent-instructions-file]"
echo ""
echo "To resume interrupted work:"
echo "  claude --resume"
echo ""
echo "Remember: Save progress frequently!"